# Generated by Django 3.2.9 on 2022-06-04 01:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.CharField(blank=True, help_text='订单编号', max_length=20, verbose_name='订单编号')),
                ('nums', models.IntegerField(blank=True, default=0, help_text='采购数量', verbose_name='采购数量')),
                ('required', models.DateField(default=django.utils.timezone.now, help_text='要求采购到位时间', verbose_name='到位时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '未标识'), (1, '工装'), (2, '检具'), (3, '模具'), (4, '采购'), (5, '交样'), (6, '试验'), (7, '产线'), (8, '产品'), (9, '开发'), (10, '供应商设计'), (11, '客户设计')], help_text='问题类别', verbose_name='类别')),
                ('severity', models.SmallIntegerField(blank=True, default=0, help_text='问题严重度', verbose_name='严重度')),
                ('desc', models.CharField(blank=True, help_text='问题描述', max_length=50, verbose_name='问题描述')),
                ('reason', models.CharField(blank=True, help_text='问题原因,最长200个字符', max_length=200, verbose_name='问题原因')),
                ('action', models.CharField(blank=True, help_text='改善措施,最长200个字符', max_length=200, verbose_name='改善措施')),
                ('target', models.DateField(default=django.utils.timezone.now, help_text='目标完成时间', verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Outsourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, help_text='工检模编号', max_length=20, verbose_name='编号')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '工装'), (1, '检具'), (2, '模具')], default='模具', help_text='工装检具模具类型选择', null=True, verbose_name='类型')),
                ('name', models.CharField(blank=True, help_text='产品名称', max_length=20, verbose_name='产品名称')),
                ('release', models.DateField(default=django.utils.timezone.now, help_text='下发制造任务书的时间', verbose_name='下单时间')),
                ('t0', models.DateField(default=django.utils.timezone.now, help_text='首次测试时间', verbose_name='首次测试时间')),
                ('approve', models.DateField(default=django.utils.timezone.now, help_text='认可的时间，需要有移交单', verbose_name='认可时间')),
                ('avatar', models.ImageField(blank=True, default='sys_img/logo_lg.png', help_text='请上传外购件图片', null=True, upload_to=project.models.user_directory_path, verbose_name='外购件图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PN', models.CharField(blank=True, help_text='发货零件号', max_length=20, verbose_name='零件号')),
                ('name', models.CharField(blank=True, help_text='产品名称', max_length=20, verbose_name='产品名称')),
                ('avatar', models.ImageField(blank=True, default='sys_img/logo_lg.png', help_text='请上传产品图片', null=True, upload_to=project.models.user_directory_path, verbose_name='产品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prg_code', models.CharField(blank=True, help_text='客户项目代码', max_length=20, verbose_name='项目代号')),
                ('name', models.CharField(blank=True, help_text='项目名称', max_length=20, verbose_name='项目名称')),
                ('pls_sn', models.CharField(blank=True, help_text='PLM创建的唯一项目号', max_length=20, verbose_name='PLM项目号')),
                ('volume', models.IntegerField(blank=True, default=0, help_text='项目预测年产量', verbose_name='年产量')),
                ('percent', models.FloatField(blank=True, default=0.0, help_text='项目当前的时间进度，仅仅从时间角度考虑', verbose_name='当前进度')),
                ('kick_off', models.DateField(default=django.utils.timezone.now, help_text='项目启动时间', verbose_name='项目启动时间')),
                ('t0_tm', models.DateField(default=django.utils.timezone.now, help_text='首件交样时间', verbose_name='首件交样时间')),
                ('ots_tm', models.DateField(default=django.utils.timezone.now, help_text='正常产线生产出来零件的时间', verbose_name='工装样件')),
                ('ppap', models.DateField(default=django.utils.timezone.now, help_text='客户批准生产的时间', verbose_name='PPAP时间')),
                ('sop', models.DateField(default=django.utils.timezone.now, help_text='客户开始量产时间，这个时候项目必须得移交', verbose_name='量产时间')),
                ('plm_tm', models.DateField(default=django.utils.timezone.now, help_text='PLM 立项时间', verbose_name='PLM 立项时间')),
                ('stage1_tm', models.DateField(default=django.utils.timezone.now, help_text='PLM 第一阶段完成时间', verbose_name='PLM 第一阶段完成时间')),
                ('stage2_tm', models.DateField(default=django.utils.timezone.now, help_text='PLM 第二阶段完成时间', verbose_name='PLM 第二阶段完成时间')),
                ('stage3_tm', models.DateField(default=django.utils.timezone.now, help_text='PLM 第三阶段完成时间', verbose_name='PLM 第三阶段完成时间')),
                ('stage4_tm', models.DateField(default=django.utils.timezone.now, help_text='PLM 第四阶段完成时间', verbose_name='PLM 第四阶段完成时间')),
                ('stage5_tm', models.DateField(default=django.utils.timezone.now, help_text='PLM 第五阶段完成时间', verbose_name='PLM 第五阶段完成时间')),
                ('Product_difficult', models.SmallIntegerField(blank=True, choices=[(2, '溢水灌'), (4, '溢水灌盖子新开'), (4, '洗涤壶'), (4, '膨胀箱'), (10, '歧管')], default=0, help_text='产品难度', null=True, verbose_name='产品难度')),
                ('line_difficult', models.SmallIntegerField(blank=True, choices=[(2, '沿用产线'), (5, '新开发产线50万内'), (10, '新开发产线超50万')], default=0, help_text='产线难度', null=True, verbose_name='产线难度')),
                ('Purchase_num', models.SmallIntegerField(blank=True, choices=[(2, '1套'), (4, '2套'), (6, '3套'), (8, '4套'), (10, '5套及以上')], default=0, help_text='新开发外购件数量，模具另算', null=True, verbose_name='外购件数量')),
                ('Fixture_num', models.SmallIntegerField(blank=True, choices=[(2, '1套'), (4, '2套'), (6, '3套'), (8, '4套'), (10, '5套及以上')], default=0, help_text='工装数量', null=True, verbose_name='工装数量')),
                ('Gauge_num', models.SmallIntegerField(blank=True, choices=[(2, '1套'), (4, '2套'), (6, '3套'), (8, '4套'), (10, '5套及以上')], default=0, help_text='检具数量', null=True, verbose_name='检具数量')),
                ('Tooling_num', models.SmallIntegerField(blank=True, choices=[(2, '1套'), (4, '2套'), (6, '3套'), (8, '4套'), (10, '5套及以上')], default=0, help_text='模具数量', null=True, verbose_name='模具数量')),
                ('Busy_factor', models.FloatField(blank=True, default=0, help_text='工作强度评价指标', null=True, verbose_name='忙碌系数')),
                ('avatar', models.ImageField(blank=True, default='sys_img/logo_lg.png', help_text='请上传项目图片', null=True, upload_to=project.models.user_directory_path, verbose_name='项目图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, help_text='工检模编号', max_length=20, verbose_name='编号')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '工装'), (1, '检具'), (2, '模具')], default='模具', help_text='工装检具模具类型选择', null=True, verbose_name='类型')),
                ('name', models.CharField(blank=True, help_text='产品名称', max_length=20, verbose_name='产品名称')),
                ('release', models.DateField(default=django.utils.timezone.now, help_text='下发制造任务书的时间', verbose_name='下单时间')),
                ('t0', models.DateField(default=django.utils.timezone.now, help_text='首次测试时间', verbose_name='首次测试时间')),
                ('approve', models.DateField(default=django.utils.timezone.now, help_text='认可的时间，需要有移交单', verbose_name='认可时间')),
                ('avatar', models.ImageField(blank=True, default='sys_img/logo_lg.png', help_text='请上传工检模图片', null=True, upload_to=project.models.user_directory_path, verbose_name='工检模图片')),
                ('equip_type', models.CharField(blank=True, help_text='设备类型，比如470T', max_length=20, verbose_name='设备类型')),
                ('cavity', models.CharField(blank=True, help_text='注塑 1+1; 吹塑 1*1', max_length=10, verbose_name='模腔数')),
                ('is_outsource', models.BooleanField(blank=True, default=False, help_text='工检模是否委外', verbose_name='是否委外')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tooling', to='project.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.SmallIntegerField(blank=True, choices=[(0, 'T0'), (1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4'), (5, 'T5'), (6, 'T6'), (7, 'T7'), (8, 'T8'), (9, 'T9'), (10, 'T10'), (11, 'T11'), (12, 'T12'), (13, 'T13'), (14, 'T14'), (15, 'T15')], help_text='试模阶段，比如T0， T1', verbose_name='试模阶段')),
                ('tryout', models.DateField(default=django.utils.timezone.now, help_text='试模时间', verbose_name='试模时间')),
                ('operation_card', models.FileField(blank=True, help_text='注塑工艺卡', null=True, upload_to=project.models.user_directory_path, verbose_name='注塑工艺卡')),
                ('dimension_rpt', models.FileField(blank=True, help_text='尺寸报告', null=True, upload_to=project.models.user_directory_path, verbose_name='尺寸报告')),
                ('minutes', models.FileField(blank=True, help_text='会议纪要', null=True, upload_to=project.models.user_directory_path, verbose_name='会议纪要')),
                ('mdf_rpt', models.FileField(blank=True, help_text='修模报告', null=True, upload_to=project.models.user_directory_path, verbose_name='修模报告')),
                ('next', models.DateField(help_text='下次试模时间', verbose_name='下次试模时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
                ('tooling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='project.tooling')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(blank=True, default=0, help_text='采购数量', verbose_name='采购数量')),
                ('required', models.DateField(default=django.utils.timezone.now, help_text='要求采购到位时间', verbose_name='到位时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
                ('outsourcing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='project.outsourcing')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'id',
            },
        ),
    ]
