# Generated by Django 3.2.9 on 2022-06-04 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, help_text='客户名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='user_info.company', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='项目负责人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='项目团队', related_name='project_team', to=settings.AUTH_USER_MODEL, verbose_name='项目团队'),
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='project.project'),
        ),
        migrations.AddField(
            model_name='outsourcing',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outsourcing', to='project.product'),
        ),
        migrations.AddField(
            model_name='issue',
            name='principal',
            field=models.ForeignKey(blank=True, help_text='问题负责人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text='问题对应的项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='project.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resume',
            field=models.ForeignKey(help_text='问题对应的履历', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='project.resume'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="可以在这里给问题打上关键字，用','隔开", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='问题标签'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='project.product'),
        ),
    ]
