# Generated by Django 3.2.9 on 2023-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='deep-diary, which is based on deep learning and web3 technical, will become your memory horsekeeper', help_text='如需投放广告，请联系深记：15055305685', max_length=200, null=True, verbose_name='广告内容')),
                ('url', models.URLField(blank=True, default='https://www.deep-diary.com', help_text='广告链接', null=True, verbose_name='广告链接')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
