# Generated by Django 3.2.9 on 2022-07-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_face_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='face',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='face',
            old_name='face_img',
            new_name='src',
        ),
    ]
