# Generated by Django 3.2.9 on 2022-08-27 06:37

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20220724_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='src',
            field=models.ImageField(blank=True, default='sys_img/unknown.jpg', help_text='请选择需要上传的人脸', null=True, upload_to=face.models.face_directory_path, verbose_name='人脸路径'),
        ),
    ]
