# Generated by Django 3.2.9 on 2022-09-07 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_alter_face_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcs',
            fields=[
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mcs', serialize=False, to='face.face')),
                ('file_upload_id', models.IntegerField(blank=True, default=0, help_text='up load file id', null=True, verbose_name='up load file id')),
                ('file_name', models.CharField(blank=True, help_text='file_name', max_length=40, null=True, verbose_name='file_name')),
                ('file_size', models.IntegerField(blank=True, default=0, help_text='file_size', null=True, verbose_name='file_size')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated_at', verbose_name='updated_at')),
                ('nft_url', models.URLField(blank=True, default='https://calibration-ipfs.filswan.com/ipfs/QmQzPDUheTnFYA7HanxwCLw3QrR7choBvh8pswF4LgxguV', help_text='相当于一个图片源，可以展示图片', null=True, verbose_name='NFT 站点')),
                ('pin_status', models.CharField(blank=True, help_text='pin_status', max_length=8, null=True, verbose_name='pin_status')),
                ('payload_cid', models.CharField(blank=True, help_text='payload_cid', max_length=80, null=True, verbose_name='payload_cid')),
                ('w_cid', models.CharField(blank=True, help_text='w_cid', max_length=100, null=True, verbose_name='w_cid')),
                ('status', models.CharField(blank=True, help_text='status', max_length=8, null=True, verbose_name='status')),
                ('deal_success', models.BooleanField(blank=True, default=False, help_text='deal_success', verbose_name='deal_success')),
                ('is_minted', models.BooleanField(blank=True, default=False, help_text='is_minted', verbose_name='is_minted')),
                ('token_id', models.CharField(blank=True, help_text='token_id', max_length=8, null=True, verbose_name='token_id')),
                ('mint_address', models.CharField(blank=True, help_text='mint_address', max_length=80, null=True, verbose_name='mint_address')),
                ('nft_tx_hash', models.CharField(blank=True, help_text='nft_tx_hash', max_length=80, null=True, verbose_name='nft_tx_hash')),
            ],
        ),
    ]
