# Generated by Django 3.2.9 on 2022-09-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_mcs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcs',
            old_name='img',
            new_name='id',
        ),
    ]
