# Generated by Django 3.2.9 on 2022-09-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_alter_facealbum_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='name',
            field=models.CharField(blank=True, default='unknown', help_text='请对该人脸进行命名', max_length=20, null=True, verbose_name='人脸名'),
        ),
    ]
