# Generated by Django 3.2.9 on 2022-09-10 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face', '0010_alter_facealbum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facealbum',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facealbum', to=settings.AUTH_USER_MODEL),
        ),
    ]
