# Generated by Django 3.2.9 on 2022-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0025_auto_20220923_2311'),
        ('face', '0011_facealbum_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facealbum',
            name='img_face',
            field=models.ManyToManyField(blank=True, default=None, help_text='对图片按人脸进行分类', through='face.Face', to='library.Img'),
        ),
    ]
