# Generated by Django 3.2.9 on 2022-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0026_auto_20220924_2149'),
        ('face', '0012_facealbum_img_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facealbum',
            name='img_face',
        ),
        migrations.AddField(
            model_name='facealbum',
            name='img',
            field=models.ManyToManyField(blank=True, default=None, help_text='对图片按人脸进行分类', related_name='facealbums', through='face.Face', to='library.Img'),
        ),
    ]
