# Generated by Django 3.2.9 on 2022-10-04 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face', '0013_auto_20220924_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facealbum',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facealbum', to=settings.AUTH_USER_MODEL),
        ),
    ]
