# Generated by Django 3.2.9 on 2022-10-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0014_alter_facealbum_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='facealbum',
            name='relationship',
            field=models.CharField(blank=True, default='unknown', help_text='relation to me', max_length=10, null=True, verbose_name='relation to me'),
        ),
    ]
