# Generated by Django 3.2.9 on 2022-10-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0015_facealbum_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facealbum',
            name='relationship',
            field=models.CharField(blank=True, default='unknown', help_text='relation to me', max_length=20, null=True, verbose_name='relation to me'),
        ),
    ]
