# Generated by Django 3.2.9 on 2023-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0031_auto_20230130_2029'),
        ('face', '0016_alter_facealbum_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facealbum',
            name='img',
            field=models.ManyToManyField(blank=True, default=None, help_text='对图片按人脸进行分类', related_name='persons', through='face.Face', to='library.Img'),
        ),
    ]
