# Generated by Django 3.2.9 on 2023-01-31 13:07

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0017_alter_facealbum_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='url',
            field=models.ImageField(blank=True, default='sys_img/unknown.jpg', help_text='保存到网络的人脸路径', null=True, upload_to=face.models.face_directory_path, verbose_name='人脸路径'),
        ),
        migrations.AlterField(
            model_name='face',
            name='src',
            field=models.ImageField(blank=True, default='sys_img/unknown.jpg', help_text='保存到本地的人脸路径', null=True, upload_to=face.models.face_directory_path, verbose_name='人脸路径'),
        ),
    ]
