# Generated by Django 3.2.9 on 2023-06-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0018_auto_20230131_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facealbum',
            name='img',
        ),
        migrations.RemoveField(
            model_name='facealbum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='facealbum',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='mcs',
            name='id',
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='FaceAlbum',
        ),
        migrations.DeleteModel(
            name='Mcs',
        ),
    ]
