# Generated by Django 3.2.9 on 2022-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, default='deep-diary, which is based on deep learning and web3 technical, will become your memory horsekeeper', help_text='相当于一个图片源，可以展示图片', max_length=200, null=True, verbose_name='NFT 站点')),
            ],
        ),
    ]
