# Generated by Django 3.2.9 on 2022-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='context',
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, default='deep-diary, which is based on deep learning and web3 technical, will become your memory horsekeeper', help_text='如需投放广告，请联系深记：15055305685', max_length=200, null=True, verbose_name='广告内容'),
        ),
        migrations.AddField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True, default='https://www.deep-diary.com', help_text='广告链接', null=True, verbose_name='广告链接'),
        ),
    ]
