# Generated by Django 3.2.9 on 2022-09-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20220827_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('-id',)},
        ),
    ]
