# Generated by Django 3.2.9 on 2022-06-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text='真实姓名', max_length=30, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'admin'), (1, 'editor'), (2, 'readonly'), (3, 'custom'), (4, 'employee'), (5, 'supplier')], help_text='用户角色', null=True, verbose_name='角色'),
        ),
    ]
