# Generated by Django 3.2.9 on 2022-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20220604_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('editor', 'editor'), ('any', 'any'), ('custom', 'custom'), ('employee', 'employee'), ('supplier', 'supplier')], default='admin', help_text='用户角色/权限', max_length=10, verbose_name='角色'),
        ),
    ]
