# Generated by Django 3.2.9 on 2022-09-10 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_info', '0004_alter_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demand', models.BooleanField(blank=True, default=False, help_text='False means suppy, True mean demand', verbose_name='is_demand')),
                ('desc', models.TextField(blank=True, help_text='Detail of SupplyDemand', verbose_name='Detail of SupplyDemand')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplydemand', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text="keyword of Detail of SupplyDemand，seperated by ','", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
