# Generated by Django 3.2.9 on 2022-09-10 07:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_info', '0005_supplydemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relation',
            field=taggit.managers.TaggableManager(blank=True, help_text='relationship to the user', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='relationship'),
        ),
    ]
