# Generated by Django 3.2.9 on 2023-06-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import user_info.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_info', '0007_demand_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='descript what position you are in charge for', max_length=100, verbose_name='job position')),
                ('start_date', models.DateField(blank=True, help_text='when is this experience started', null=True, verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, help_text='when is this experience end_date', null=True, verbose_name='end_date')),
                ('name', models.CharField(help_text='the title of this experience', max_length=30, verbose_name='name')),
                ('desc', models.CharField(help_text='the detail of this experience', max_length=300, verbose_name='description')),
                ('achievement', models.CharField(help_text='fill the achievement you got', max_length=100, verbose_name='achievement')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user_info.company')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='sys_img/logo_lg.png', help_text='请上传文件', null=True, upload_to=user_info.models.user_upload_file, verbose_name='文件')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='sys_img/logo_lg.png', help_text='请上传图片', null=True, upload_to=user_info.models.user_upload_img, verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, help_text='Detail of SupplyDemand', verbose_name='Detail of SupplyDemand')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='首次创建的时间', verbose_name='首次创建的时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='最后更新的时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='demand',
            name='name',
            field=models.CharField(blank=True, help_text='title of demand', max_length=30, verbose_name='title of demand'),
        ),
        migrations.AddField(
            model_name='profile',
            name='feat',
            field=models.BinaryField(blank=True, help_text='已识别的人脸特征向量', null=True, verbose_name='人脸特征'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='desc',
            field=models.TextField(blank=True, help_text='description of Demand', verbose_name='Detail of Demand'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="keyword of Detail of SupplyDemand，separated by ','", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.AddField(
            model_name='resource',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="keyword of Detail of SupplyDemand，seperated by ','", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='image',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_info.demand'),
        ),
        migrations.AddField(
            model_name='image',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_info.experience'),
        ),
        migrations.AddField(
            model_name='image',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_info.resource'),
        ),
        migrations.AddField(
            model_name='file',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_info.demand'),
        ),
        migrations.AddField(
            model_name='file',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_info.experience'),
        ),
        migrations.AddField(
            model_name='file',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_info.resource'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(through='user_info.Experience', to=settings.AUTH_USER_MODEL),
        ),
    ]
