# Generated by Django 3.2.9 on 2023-06-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_rename_feat_profile_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('user', 'User'), ('customer', 'Customer'), ('employee', 'Employee'), ('supplier', 'Supplier')], default='user', help_text='用户角色/权限', max_length=10, verbose_name='角色'),
        ),
        migrations.DeleteModel(
            name='SupplyDemand',
        ),
    ]
