# Generated by Django 3.2.9 on 2023-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_alter_recontact_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recontact',
            options={'get_latest_by': 'id', 'ordering': ('re_from',)},
        ),
        migrations.AlterField(
            model_name='recontact',
            name='relation',
            field=models.SmallIntegerField(blank=True, choices=[(0, '我'), (1, '妻子'), (2, '丈夫'), (3, '儿子'), (4, '女儿'), (5, '爸爸'), (6, '妈妈'), (7, '爷爷'), (8, '奶奶'), (9, '外公'), (10, '外婆'), (11, '家人'), (12, '哥哥'), (13, '姐姐'), (14, '弟弟'), (15, '妹妹'), (16, '亲戚'), (17, '男朋友'), (18, '女朋友'), (19, '同事'), (20, '朋友'), (21, '同学'), (22, '闺蜜'), (23, '客户'), (24, '供应商'), (25, '合作伙伴'), (26, '其他')], default='friend', help_text='re_from和re_to的关系', verbose_name='关系'),
        ),
    ]
