# Generated by Django 3.2.9 on 2023-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_auto_20230827_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_pinyin',
            field=models.CharField(blank=True, help_text='真实姓名全拼', max_length=20, null=True, verbose_name='真实姓名全拼'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lazy_pinyin',
            field=models.CharField(blank=True, help_text='真实姓名首拼', max_length=20, null=True, verbose_name='真实姓名首拼'),
        ),
    ]
