# Generated by Django 3.2.9 on 2023-10-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_info', '0014_auto_20230827_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='user_info.company')),
                ('is_located', models.BooleanField(blank=True, default=False, help_text='是否有GPS 信息', verbose_name='是否有GPS 信息')),
                ('longitude_ref', models.CharField(blank=True, default='E', help_text='东西经', max_length=5, null=True, verbose_name='东西经')),
                ('longitude', models.FloatField(blank=True, default=0.0, help_text='经度', max_length=20, null=True, verbose_name='经度')),
                ('latitude_ref', models.CharField(blank=True, default='N', help_text='南北纬', max_length=5, null=True, verbose_name='南北纬')),
                ('latitude', models.FloatField(blank=True, default=0.0, help_text='纬度', max_length=20, null=True, verbose_name='纬度')),
                ('altitude_ref', models.FloatField(blank=True, default=0.0, help_text='参考高度', max_length=5, null=True, verbose_name='参考高度')),
                ('altitude', models.FloatField(blank=True, default=0.0, help_text='高度', max_length=20, null=True, verbose_name='高度')),
                ('location', models.CharField(blank=True, default='No GPS', help_text='拍摄地', max_length=50, null=True, verbose_name='拍摄地')),
                ('district', models.CharField(blank=True, default='No GPS', help_text='拍摄区县', max_length=20, null=True, verbose_name='拍摄区县')),
                ('city', models.CharField(blank=True, default='No GPS', help_text='拍摄城市', max_length=20, null=True, verbose_name='拍摄城市')),
                ('province', models.CharField(blank=True, default='No GPS', help_text='拍摄省份', max_length=20, null=True, verbose_name='拍摄省份')),
                ('country', models.CharField(blank=True, default='No GPS', help_text='拍摄国家', max_length=20, null=True, verbose_name='拍摄国家')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, help_text='title of Resource', max_length=30, verbose_name='title of Resource'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="keyword of Detail of Demand，separated by ','", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='recontact',
            name='re_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_from_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recontact',
            name='re_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_to_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recontact',
            name='relation',
            field=models.SmallIntegerField(blank=True, choices=[(0, '我'), (1, '妻子'), (2, '丈夫'), (3, '儿子'), (4, '女儿'), (5, '爸爸'), (6, '妈妈'), (7, '爷爷'), (8, '奶奶'), (9, '外公'), (10, '外婆'), (11, '家人'), (12, '哥哥'), (13, '姐姐'), (14, '弟弟'), (15, '妹妹'), (16, '亲戚'), (17, '男朋友'), (18, '女朋友'), (19, '同事'), (20, '朋友'), (21, '同学'), (22, '闺蜜'), (23, '客户'), (24, '供应商'), (25, '合作伙伴'), (26, '其他')], default=26, help_text='re_from和re_to的关系', verbose_name='关系'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='desc',
            field=models.TextField(blank=True, help_text='Detail of Resource', verbose_name='Detail of Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text="keyword of Detail of Resource，separated by ','", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='recontact',
            unique_together={('re_from', 're_to', 'relation')},
        ),
    ]
