# Generated by Django 3.2.9 on 2023-10-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0015_auto_20231002_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='demand',
            field=models.ForeignKey(blank=True, help_text='the files of this demand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_info.demand', verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='file',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='the files of this experience', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_info.experience', verbose_name='工作经验'),
        ),
        migrations.AlterField(
            model_name='file',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='the files of this resource', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_info.resource', verbose_name='资源'),
        ),
        migrations.AlterField(
            model_name='image',
            name='demand',
            field=models.ForeignKey(blank=True, help_text='the images of this demand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_info.demand', verbose_name='需求'),
        ),
        migrations.AlterField(
            model_name='image',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='the images of this experience', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_info.experience', verbose_name='工作经验'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='the images of this resource', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_info.resource', verbose_name='资源'),
        ),
    ]
