# Generated by Django 3.2.9 on 2023-10-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0016_auto_20231002_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='src',
        ),
    ]
