# Generated by Django 3.2.9 on 2023-10-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0018_auto_20231003_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duty',
            field=models.CharField(help_text='the duty of this experience', max_length=300, null=True, verbose_name='responsibility'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='achievement',
            field=models.CharField(blank=True, help_text='fill the achievement you got', max_length=100, null=True, verbose_name='achievement'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='desc',
            field=models.CharField(help_text='the brief description of this experience', max_length=300, null=True, verbose_name='description'),
        ),
    ]
