# Generated by Django 3.2.9 on 2023-10-04 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0019_auto_20231003_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_PyFull',
            field=models.CharField(blank=True, help_text='公司名称全拼', max_length=30, null=True, verbose_name='公司名称全拼'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(related_name='companies', through='user_info.Experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_PyInitial',
            field=models.CharField(blank=True, help_text='公司名称拼音首字母', max_length=20, null=True, verbose_name='公司名称拼音首字母'),
        ),
    ]
