# Generated by Django 3.2.9 on 2023-10-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0020_auto_20231004_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_PyFull',
            field=models.CharField(blank=True, help_text='公司名称全拼', max_length=60, null=True, verbose_name='公司名称全拼'),
        ),
    ]
