# Generated by Django 3.2.9 on 2023-10-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0021_alter_company_name_pyfull'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assert',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asserts', serialize=False, to='user_info.profile')),
                ('face_cnt', models.IntegerField(default=0, help_text='人脸数', verbose_name='人脸数')),
                ('img_cnt', models.IntegerField(default=0, help_text='图片数', verbose_name='图片数')),
                ('video_cnt', models.IntegerField(default=0, help_text='视频数', verbose_name='视频数')),
                ('audio_cnt', models.IntegerField(default=0, help_text='音频数', verbose_name='音频数')),
                ('diary_cnt', models.IntegerField(default=0, help_text='日记数', verbose_name='日记数')),
                ('gps_cnt', models.IntegerField(default=0, help_text='GPS数', verbose_name='GPS数')),
                ('friend_cnt', models.IntegerField(default=0, help_text='朋友数', verbose_name='朋友数')),
            ],
        ),
    ]
