# Generated by Django 3.2.9 on 2023-10-22 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0022_assert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='user_info.company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='desc',
            field=models.CharField(blank=True, help_text='the brief description of this experience', max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duty',
            field=models.CharField(blank=True, help_text='the duty of this experience', max_length=300, null=True, verbose_name='responsibility'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(blank=True, help_text='the title of this experience', max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
