# Generated by Django 3.2.9 on 2023-10-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0023_auto_20231022_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('profile', 'company', 'name')},
        ),
    ]
